/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import main.Application;
import org.junit.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
        Application classUnderTest = new Application();
    }
}
